// packages/web/src/routes/artists/[id]/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";

  import type { Album, Artist } from "@peppermint/shared";
	import HeroLayout from "$lib/layout/hero-layout.svelte";
  import MenuCard from "$lib/components/menu-card/index.svelte";
  import Carousel from "$lib/components/carousel/index.svelte";
  import Link from "$lib/components/ds/link/index.svelte";
  import { queryOne } from "$lib/api";
  import { supabase } from "$lib/supabase";

  type QueryResult = Artist & {
    artist_to_album: {
      album: Album;
    }[];
  };

  const { data } = queryOne<QueryResult>(
    async () =>
      await supabase
        .from("artist")
        .select("*, artist_to_album(album_id, album(*))")
        .eq("id", $page.params.id)
        .single(),
    [{ table: "artist", filter: `id=eq.${$page.params.id}` }]
  );
</script>

{#if $data}
  {@const albums = $data.artist_to_album.map((doc) => doc.album)}
  <HeroLayout>
    <div slot="hero" class="h-full relative" style="background-image: url('{$data.hero_image}'); background-size: cover; background-position: center;">
      <div class="absolute top-0 h-20 w-full bg-gradient-to-b from-black to-transparent" />
      <div class="absolute bottom-0 px-4 pb-7 w-full bg-gradient-to-t from-black to-transparent">
        <div class="max-w-[1100px] mx-auto flex flex-col gap-4">
          <h2 class="text-white text-3xl font-semibold">
            {$data.name}
          </h2>
        </div>
      </div>
    </div>
      
    <div class="flex flex-col gap-8">
      <div class="flex flex-col gap-6">
        <Carousel loading={!albums} title="Albums" description="{$data.name} has {albums.length} album{albums.length === 1 ? "" : "s"} on Peppermint">
          {#each (albums || []) as album}
            <a class="w-[43%] flex-shrink-0" href={`/albums/${album.id}`}>
              <MenuCard title={album.name} image={album.image} />
            </a>
          {/each}
        </Carousel>
      </div>

      <div class="flex flex-col gap-1">
        <h3 class="text-xl font-semibold text-slate-700">Want to find Peppermint merch from {$data.name}?</h3>
        <p class="text-sm">Check out a shows to get your unique copy!  
        View upcoming shows <Link href="https://bennysidelinger.com/shows" blank>here.</Link></p>
      </div>
    </div>
  </HeroLayout>
{:else}
  <HeroLayout loading />
{/if}

// packages/native/app/artist/[id].tsx
import React from "react";
import { router, Stack, useLocalSearchParams } from "expo-router";
import { View, Text, TouchableOpacity, ImageBackground } from "react-native";
// import { useSafeAreaInsets } from "react-native-safe-area-context";
// import { Ionicons } from "@expo/vector-icons";
import { Artist, Album } from "@peppermint/shared";

import { supabase } from "~/utils/supabase";
import { queryOne } from "~/utils/supabaseQuery";
// import ScreenLoader from "~/components/ScreenLoader";
import Hero from "~/components/layout/hero/Hero";
import { LinearGradient } from "expo-linear-gradient";
import PlayerScreen from "~/components/layout/PlayerScreen";
// import { formatDuration } from "~/utils/formatting";
// import { useSafeAreaInsets } from "react-native-safe-area-context";

type QueryResult = Artist & {
  artist_to_album: {
    album: Album;
  }[];
};

export default function AlbumScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  // const { bottom } = useSafeAreaInsets();

  const { data: artist } = queryOne<QueryResult>(
    async () =>
      await supabase
        .from("artist")
        .select("*, artist_to_album(album_id, album(*))")
        .eq("id", id)
        .single(),
    [{ table: "artist", filter: `id=eq.${id}` }]
  );

  function goToAlbum(albumId: number) {
    router.push({
      pathname: "/album/[id]",
      params: { id: albumId },
    });
  }

  return (
    <>
      <Stack.Screen options={{ headerShown: false }} />
      <PlayerScreen>
        <Hero image={artist ? artist.hero_image : ""} title={artist?.name}>
          <View className="absolute bottom-0 left-2">
            <Text className="text-4xl font-semibold text-white">{artist?.name}</Text>
          </View>
        </Hero>

        {artist && (
          <View className="flex flex-col gap-4 p-4">
            <Text className="text-2xl font-semibold">Albums</Text>

            <View className="grid grid-cols-2 gap-4">
              {artist.artist_to_album.map(({ album }) => (
                <TouchableOpacity
                  className="relative flex  aspect-square w-1/2 flex-col justify-end overflow-hidden rounded-lg"
                  key={album.id}
                  onPress={() => goToAlbum(album.id)}>
                  <ImageBackground
                    resizeMode="cover"
                    className="absolute inset-0 h-full w-full rounded-lg border border-gray-400"
                    source={{ uri: album.image }}
                  />

                  <LinearGradient
                    className="rounded-b-md"
                    colors={["transparent", "rgba(0,0,0,0.8)"]}
                    locations={[0.5, 1]}
                    style={{
                      position: "absolute",
                      left: 0,
                      right: 0,
                      top: 0,
                      bottom: 0,
                    }}
                  />

                  <View className="flex flex-col gap-1 p-2">
                    <Text className="text-xl font-semibold text-white">{album.name}</Text>
                  </View>
                </TouchableOpacity>
              ))}
            </View>
          </View>
        )}
      </PlayerScreen>
    </>
  );
}
